theme: jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
include:
  - Phyllotaxis/README.md
  - Times-Tables/README.md
  - Mandala/README.md
  - Chaos-Game/README.md
  - Triangle/README.md
  - Ulam-Spiral/README.md
